### ISSUE TITLE
Possibly include pictures?

### ISSUE THREAD

**Issue by michael105** [solarkennedy/ascii-art-converter-comparison#1]
Firstly, thanks for your great work.
However, it would be really wonderful, 
if you could possibly upload the example images to github.
I wouldn't have to install all converters then,
only the ones, I like..
Best wishes, Michael

**Comment by solarkennedy** [comment]
They are all here in this repo, although not in folder:
https://github.com/solarkennedy/xkyle.com/blob/master/static/uploads/bender.TerminalImageViewer.png

You can pick the ones you want referenced from the blog article:
http://www.xkyle.com/Another-Comparison-of-Image-to-ASCII-Conversion-Tools-2017/

**Comment by michael105** [comment]
Thanks. :grin: Me doing further .. uh just thanks :+1: 
btw. Are you possibly interested in participating in a new opensource project?
I'm working on a launch.. but, to be honest, albeit I nearly don't sleep anymore,
it's MUCH work for one on it's own.
I've got a good concept, I believe.
And I've got one or two ideas, regarding ascii-art.
(Somehow you have to get attention..)
Are you still in ansii art?
Would be something like a textfilter

**Comment by solarkennedy** [comment]
No thank you.
